### ISSUE TITLE
hdf5 vs. h5df

### ISSUE THREAD

**Issue by spahlimi** [outofculture/metaarray#2]
Hi, 

MetaArray cannot be installed with pi currently, because in setup.py it requires the package "hdf5" which is not available on pypi. I think this is a little mistake and instead of 
`install_requires=["numpy", "hdf5"],`
it should have been:
`install_requires=["numpy", "h5df"],`

Can you fix this and publish a new metaarray release?

Thanks!

**Comment by outofculture** [comment]
Fixed in version 2.0.3 on pypi. Thank you!
