### ISSUE TITLE
Can not evaluate strings of form "3000L"

### ISSUE THREAD

**Issue by pbmanis** [outofculture/metaarray#3]
This particular issue  has been a problem for several years, even when metaarray was part of pyqtgraph. I have manually patched this several times, but perhaps it is time for a proper solution.

Camera data (in acq4) may have values written with "L" appended to the integer.  This causes a failure in readHDF5Meta, where the value string cannot be evaluated. 

A simple solution to this is (lines 897-903 of __init__.py):

            if isinstance(val, str):  # strings need to be re-evaluated to their original types
                if val[-1] == 'L':  # strip trailing "long" 
                    val = val[:-1]
                try:
                    val = eval(val)
                except:
                    raise Exception('Can not evaluate string: "%s"' % val)

A more robust solution might involve also capturing 'U', 'l' (lower case) or other characters that might be appended to a number. However, the only instance I have encountered in data stored by Acq4 is the 'L'.

**Comment by pbmanis** [comment]
One more try?
Tested in wild - doesn't quite work. 
the line (891):
numstrs  = map... 
has to be 
numstrs = list(map...). 
Otherwise, the tests on 898 the val fail (tests are against the map iterator, not its results).

**Comment by outofculture** [comment]
Huh. `'0' in map(str, range(0, 10))` works on my system, but I'll admit I don't have a file with data in this format to test it. I'll make that change, but I wonder if something else might be awry. If you can upload a piece of data that triggers this bug, I can also test things myself.

**Comment by pbmanis** [comment]
Hi Martin,
Here's a file - I had to compress it, since it is an ".ma" (hdf5) file from acq4 and GitHub did not like the '.ma' extension.
I'm using python3.10.4. When I generate the map on the command line, I get an iterator. 
Looking at the MultiClamp1.ma file, and digging down into the data structure,  info/2/DAQ/command/numPts has a value of 3000L, which is the currently offending data point. 'numPts' in the info/2/DAQ/primary and info/2/DAQ/secondary have the same value. While this could (and should?) be cleaned up in acq4 itself, we literally have millions of files with this format. 
[MultiClamp1.ma.zip](https://github.com/outofculture/metaarray/files/9855327/MultiClamp1.ma.zip).
Thanks, --Paul

**Comment by outofculture** [comment]
Ah ha! I see now:
```python
numstrs = map(str, range(0, 10))
'1' in numstrs  # => True
'1' in numstrs  # => False
```
The generator gets used up after the first membership test. That's one expression that doesn't behave the same when extracted into a variable.

Thanks again!
